//
//  PatternCreationNewWorker.swift
//  ArchitecturePatternsAppV2
//
//  Created by Олег Зуев on 29.11.2025.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

class PatternCreationWorker {
    private let remoteStore: PatternRemoteStoreProtocol
    private let dataStore: PatternStorageProtocol

    init(remoteStore: PatternRemoteStoreProtocol, dataStore: PatternStorageProtocol) {
        self.remoteStore = remoteStore
        self.dataStore = dataStore
    }
    
    func addNewPatternRemote(_ pattern: PatternModel, completion: ((Result<Void, Error>) -> Void)? = nil) {
        remoteStore.save(pattern, completion: completion)
    }
    
    func addNewPatternLocal(_ pattern: PatternModel) throws {
        try dataStore.addNewPattern(pattern)
    }
}
