//
//  PatternCreationNewWorker.swift
//  ArchitecturePatternsAppV2
//
//  Created by Олег Зуев on 29.11.2025.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

class PatternCreationWorker {
    private let remoteStore: PatternRemoteStoreProtocol

    init(remoteStore: PatternRemoteStoreProtocol) {
        self.remoteStore = remoteStore
    }
    
    func addNewPattern(_ pattern: PatternModel, completion: ((Result<Void, Error>) -> Void)? = nil) {
        remoteStore.save(pattern, completion: completion)
    }
}
