//
//  PatternCreationNewWorker.swift
//  ArchitecturePatternsAppV2
//
//  Created by Олег Зуев on 29.11.2025.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

class PatternCreationWorker {
    let storage: PatternStorageProtocol
    
    init(dataStore: PatternStorageProtocol) {
        self.storage = dataStore
    }
    
    func addNewPattern(_ newPattern: PatternModel) throws {
        try storage.addNewPattern(newPattern)
    }
}
