//
//  PatternCreationNewRouter.swift
//  ArchitecturePatternsAppV2
//
//  Created by Олег Зуев on 29.11.2025.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import PhotosUI

@objc protocol PatternCreationRoutingLogic {
    func close()
    func showBottomSheet()
    func showImageSourceAlert()
    func showImagePicker()
    func showCreationErrorAlert()
}


class PatternCreationRouter: NSObject, PatternCreationRoutingLogic {
    weak var viewController: PatternCreationViewController?
    
    func close() {
        viewController?.navigationController?.popViewController(animated: true)
    }
    
    func showBottomSheet() {
        let bottomSheet = BottomSheetViewController(selectedType: nil)
        bottomSheet.delegate = viewController
        viewController?.present(bottomSheet, animated: true)
    }
    
    func showImageSourceAlert() {
        let actionSheet = UIAlertController(title: nil, message: nil, preferredStyle: .actionSheet)
        let photo = UIAlertAction(title: "Фото", style: .default) { _ in
            self.showImagePicker()
        }
        let file = UIAlertAction(title: "Файлы", style: .destructive) { _ in
            // TODO Работа с файлами
        }
        
        let cancel = UIAlertAction(title: "Отмена", style: .cancel)
        
        actionSheet.addAction(photo)
        actionSheet.addAction(file)
        actionSheet.addAction(cancel)
        
        viewController?.present(actionSheet, animated: true)
    }
    
    func showImagePicker() {
        var config = PHPickerConfiguration(photoLibrary: .shared())
        config.filter = .images
        config.selectionLimit = 1
        
        let picker = PHPickerViewController(configuration: config)
        picker.delegate = viewController
        viewController?.present(picker, animated: true)
    }
    
    func showCreationErrorAlert() {
        let alert = UIAlertController(
            title: "Заполните поля",
            message: "Внесите имя и выберете тип паттерна",
            preferredStyle: .alert
        )
        
        let okButton = UIAlertAction(title: "ОК", style: .default)
        alert.addAction(okButton)
        viewController?.present(alert, animated: true)
    }
    
}
