//
//  PatternCreationNewInteractor.swift
//  ArchitecturePatternsAppV2
//
//  Created by Олег Зуев on 29.11.2025.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol PatternCreationBusinessLogic {
    func createNewPattern(request: PatternCreation.AddNewPattern.Request)
}

class PatternCreationNewInteractor: PatternCreationBusinessLogic {
    
    var worker: PatternCreationWorker
    
    init(worker: PatternCreationWorker) {
        self.worker = worker
    }
    
    func createNewPattern(request: PatternCreation.AddNewPattern.Request) {
        let newPattern = request.newPattern
        
        
       worker.addNewPattern(newPattern) { result in
            switch result {
            case .success():
                print ("Pattern was created")
            case .failure(let error):
                print ("Pattern was created", error)
            }
            
        }    
    }
}
