//
//  DesignPatternsCSPresenter.swift
//  ArchitecturePatternsAppV2
//
//  Created by Олег Зуев on 25.11.2025.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

protocol DesignPatternsCSPresentationLogic {
    func presentList(response: DesignPatterns.LoadList.Response)
    func presentToggleFavorite(response: DesignPatterns.ToggleFavorite.Response)
    func presentDelete(response: DesignPatterns.RowDelete.Response)
    func presentError(response: DesignPatterns.Error.Response)
}

class DesignPatternsPresenter: DesignPatternsCSPresentationLogic {
    
    weak var viewController: DesignPatternsDisplayLogic?
    
    func presentList(response: DesignPatterns.LoadList.Response) {
        let sectionsVM: [DesignPatterns.LoadList.ViewModel.Section] =
            response.sections.map { domainSections in
                guard let first = domainSections.first else {
                    return .init(title: "", rows: [])
                }
                let title = first.type.title
                let rows = domainSections.map { pattern in
                    PatternViewModel(domain: pattern)
                }
                
                return .init(title: title, rows: rows)
            }
        
        let viewModel = DesignPatterns.LoadList.ViewModel(sections: sectionsVM)
        viewController?.displayList(viewModel: viewModel)
    }
    
    func presentToggleFavorite(response: DesignPatterns.ToggleFavorite.Response) {
        let vm = PatternViewModel(domain: response.updatedPattern)
        let viewModel = DesignPatterns.ToggleFavorite.ViewModel(
            indexPath: response.indexPath,
            updatedRow: vm
        )
        viewController?.displayToggleFavorite(viewModel: viewModel)
    }
    
    func presentDelete(response: DesignPatterns.RowDelete.Response) {
        let viewModel = DesignPatterns.RowDelete.ViewModel(indexPath: response.indexPath)
        viewController?.displayDelete(viewModel: viewModel)
    }
    
    func presentError(response: DesignPatterns.Error.Response) {
        let message = "Ошибка: \(response.error)"
        let viewModel = DesignPatterns.Error.ViewModel(message: message)
        viewController?.displayError(viewModel: viewModel)
    }

}
