//
//  DesignPatternsCSModels.swift
//  ArchitecturePatternsAppV2
//
//  Created by Олег Зуев on 25.11.2025.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
import Foundation

enum DesignPatterns {
 
    // MARK: Use cases
    enum LoadList {
        struct Request {}
        
        struct Response {
            let sections: [[PatternModel]]
        }
        
        struct ViewModel {
            struct Section {
                let title: String
                var rows: [PatternViewModel]
            }
            
            let sections: [Section]
        }
    }
    
    enum ToggleFavorite {
        struct Request {
            let indexPath: IndexPath
        }
        struct Response {
            let indexPath: IndexPath
            let updatedPattern: PatternModel
        }
        struct ViewModel {
            let indexPath: IndexPath
            let updatedRow: PatternViewModel
        }
    }
    
    enum RowDelete {
        struct Request {
            let indexPath: IndexPath
        }
        struct Response {
            let indexPath: IndexPath
        }
        struct ViewModel {
            let indexPath: IndexPath
        }
    }
    
    enum Select {
        struct Request {
            let indexPath: IndexPath
        }
    }
    
    enum Error {
        struct Response {
            let error: Error
        }
        
        struct ViewModel {
            let message: String
        }
    }
}
