//
//  DesignPatternsCSWorker.swift
//  ArchitecturePatternsAppV2
//
//  Created by Олег Зуев on 25.11.2025.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

class DesignPatternsWorker {
    
    private let remoteStore: PatternRemoteStoreProtocol

    init(remoteStore: PatternRemoteStoreProtocol) {
        self.remoteStore = remoteStore
    }
    
    func fetchAllPatterns(completion: @escaping (Result<[PatternModel], Error>) -> Void) {
        remoteStore.fetchAll(completion: completion)
    }
    
    func updatePattern(_ pattern: PatternModel, completion: ((Result<Void, Error>) -> Void)? = nil) {
        remoteStore.save(pattern, completion: completion)
    }
    
    func deletePattern(_ pattern: PatternModel, completion: ((Result<Void, Error>) -> Void)? = nil) {
        remoteStore.delete(id: pattern.id, completion: completion)
    }
    
    func incrementViewCounterFor(_ model: PatternModel, completion: ((Result<Void, Error>) -> Void)?) {
        remoteStore.incrementViewCounterFor(model, completion: completion)
    }
    
//    func incrementViews(for model: PatternModel) throws {
//        try storage.incrementViewCounterFor(model: model)
//    }
}
