//
//  DesignPatternsCSInteractor.swift
//  ArchitecturePatternsAppV2
//
//  Created by Олег Зуев on 25.11.2025.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
import Foundation

protocol DesignPatternsBusinessLogic {
    func loadPatterns(request: DesignPatterns.LoadList.Request)
    func toggleFavorite(request: DesignPatterns.ToggleFavorite.Request)
    func deletePattern(request: DesignPatterns.RowDelete.Request)
    func selectPattern(request: DesignPatterns.Select.Request)
}

protocol DesignPatternsDataStore {
    var sections: [[PatternModel]] { get set }
    var selectedPattern: PatternModel? { get set }
}

final class DesignPatternsInteractor: DesignPatternsBusinessLogic, DesignPatternsDataStore {
   
    var presenter: DesignPatternsCSPresentationLogic?
    let worker: DesignPatternsWorker
    
    var sections: [[PatternModel]] = []
    var selectedPattern: PatternModel?
    
    init(worker: DesignPatternsWorker) {
        self.worker = worker
    }
    
    func loadPatterns(request: DesignPatterns.LoadList.Request) {
        do {
            let all = try worker.fetchAllPatterns()
            sections = Self.makeSections(from: all)
            let response = DesignPatterns.LoadList.Response(sections: sections)
            presenter?.presentList(response: response)
        } catch {
            // Тут можно обработать ошибку
        }
    }
    
    func toggleFavorite(request: DesignPatterns.ToggleFavorite.Request) {
        let indexPath = request.indexPath
        guard var pattern = getPattern(at: indexPath) else { return }
        pattern.isFavorite.toggle()
        
        do {
            try worker.updatePattern(pattern)
            sections[indexPath.section][indexPath.row] = pattern
            let response = DesignPatterns.ToggleFavorite.Response(
                indexPath: indexPath,
                updatedPattern: pattern
            )
            presenter?.presentToggleFavorite(response: response)
        } catch {
            // Тут можно обработать ошибку
        }
    }
    
    func deletePattern(request: DesignPatterns.RowDelete.Request) {
        let indexPath = request.indexPath
        guard let pattern = getPattern(at: indexPath) else { return }
        
        do {
            try worker.deletePattern(pattern)
            sections[indexPath.section].remove(at: indexPath.row)
            let response = DesignPatterns.RowDelete.Response(indexPath: indexPath)
            presenter?.presentDelete(response: response)
        } catch {
            // Тут можно обработать ошибку
        }
    }
    
    func selectPattern(request: DesignPatterns.Select.Request) {
        let indexPath = request.indexPath
        guard let pattern = getPattern(at: indexPath) else { return }
        selectedPattern = pattern
        
        do {
            try worker.incrementViews(for: pattern)
        } catch {
            // Тут можно обработать ошибку 
        }
    }
    
}

#warning("Глубже осознать")
private extension DesignPatternsInteractor {
    static func makeSections(from all: [PatternModel]) -> [[PatternModel]] {
        let grouped = Dictionary(grouping: all, by: {$0.type})
        return PatternType.allCases.map { type in
            grouped[type] ?? []
        }
    }
    
    func getPattern(at indexPath: IndexPath) -> PatternModel? {
        guard sections.indices.contains(indexPath.section),
              sections[indexPath.section].indices.contains(indexPath.row) else {
            return nil
        }
        return sections[indexPath.section][indexPath.row]
    }
}
