//
//  DesignPatternsCSViewController.swift
//  ArchitecturePatternsAppV2
//
//  Created by Олег Зуев on 25.11.2025.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DesignPatternsDisplayLogic: AnyObject {
    func displayList(viewModel: DesignPatterns.LoadList.ViewModel)
    func displayToggleFavorite(viewModel: DesignPatterns.ToggleFavorite.ViewModel)
    func displayDelete(viewModel: DesignPatterns.RowDelete.ViewModel)
    func displayError(viewModel: DesignPatterns.Error.ViewModel)
}

class DesignPatternsViewController: BaseContentViewController {
        
    var interactor: DesignPatternsBusinessLogic?
    var router: (NSObjectProtocol & DesignPatternsRoutingLogic & DesignPatternsDataPassing)?
    
    // MARK: - Properties
    private var tableView = UITableView()
    
    // MARK: - Data
    
    private var sections: [DesignPatterns.LoadList.ViewModel.Section] = []
    
    // MARK: - Life cycle methods
    override func viewDidLoad() {
        super.viewDidLoad()
        setupView()
        loadData()
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        loadData()
    }
    
    @objc override func didTapLeftButton() {
        router?.openCreationMenu()
    }
    
    @objc override func didTapRightButton() {
        router?.toggleSideMenu()
    }
    
}

// MARK: - Private Methods
private extension DesignPatternsViewController {
    // MARK: - View Setup
    func setupView() {
        setupUI()
        setupTableView()
        addViews()
        setupConstraints()
    }
    
    // MARK: - UI Setup
    func setupUI() {
        self.view.backgroundColor = UIColor.systemBackground
    }
    
    // MARK: - Table Setup
    private func setupTableView() {
        tableView.register(PatternTableViewCell.self, forCellReuseIdentifier: PatternTableViewCell.identifier)
        tableView.register(HeaderView.self, forHeaderFooterViewReuseIdentifier: HeaderView.identifier)
        tableView.delegate = self
        tableView.dataSource = self
        tableView.separatorStyle = .none
        tableView.sectionHeaderTopPadding = 0
    }
    
    // MARK: - Add Views
    private func addViews() {
        view.addSubview(tableView)
    }
    
    // MARK: - Constraints Setup
    private func setupConstraints() {
        tableView.snp.makeConstraints { make in
            make.edges.equalToSuperview()
        }
    }
    
    func loadData() {
        let request = DesignPatterns.LoadList.Request()
        interactor?.loadPatterns(request: request)
    }
}

// MARK: - UITableViewDataSource
extension DesignPatternsViewController: UITableViewDataSource {
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        sections[section].rows.count
    }
    
    func numberOfSections(in tableView: UITableView) -> Int {
        sections.count
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        guard let cell = tableView.dequeueReusableCell(withIdentifier: PatternTableViewCell.identifier, for: indexPath) as? PatternTableViewCell else { return UITableViewCell() }
    
        let vm = sections[indexPath.section].rows[indexPath.row]


        cell.configure(with: vm, isFirstCell: indexPath.row == 0)
        cell.delegate = self
        
        return cell
    }
}

// MARK: - UITableViewDelegate
extension DesignPatternsViewController: UITableViewDelegate {
    func tableView(_ tableView: UITableView, viewForHeaderInSection section: Int) -> UIView? {
        guard let header = tableView.dequeueReusableHeaderFooterView(withIdentifier: HeaderView.identifier) as? HeaderView else {return UITableViewHeaderFooterView()}
        let headerTitle = PatternType.allCases[section].title
        header.configureUI(with: headerTitle)
        return header
    }
    
    func tableView(_ tableView: UITableView, heightForHeaderInSection section: Int) -> CGFloat {
        return 45
    }
    
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        let request = DesignPatterns.Select.Request(indexPath: indexPath)
        interactor?.selectPattern(request: request)
        router?.openPatternDetails()
    }
    
    func tableView(_ tableView: UITableView, trailingSwipeActionsConfigurationForRowAt indexPath: IndexPath) -> UISwipeActionsConfiguration? {
        let deleteAction = UIContextualAction(style: .destructive, title: "Delete") { _, _, _ in
            let request = DesignPatterns.RowDelete.Request(indexPath: indexPath)
            self.interactor?.deletePattern(request: request)
        }
        
        return UISwipeActionsConfiguration(actions: [deleteAction])
    }
}

extension DesignPatternsViewController: DesignPatternsDisplayLogic {
    func displayList(viewModel: DesignPatterns.LoadList.ViewModel) {
        sections = viewModel.sections
        tableView.reloadData()
    }
    
    func displayToggleFavorite(viewModel: DesignPatterns.ToggleFavorite.ViewModel) {
        let indexPath = viewModel.indexPath
        
        guard sections.indices.contains(indexPath.section),
              sections[indexPath.section].rows.indices.contains(indexPath.row)
        else { return }
        
        sections[indexPath.section].rows[indexPath.row] = viewModel.updatedRow
        tableView.reloadRows(at: [indexPath], with: .none)
    }
    
    func displayDelete(viewModel: DesignPatterns.RowDelete.ViewModel) {
        let indexPath = viewModel.indexPath
        
        guard sections.indices.contains(indexPath.section),
              sections[indexPath.section].rows.indices.contains(indexPath.row)
        else { return }
        
        sections[indexPath.section].rows.remove(at: indexPath.row)
        
        if sections[indexPath.section].rows.isEmpty {
            sections.remove(at: indexPath.section)
            tableView.deleteSections(IndexSet(integer: indexPath.section), with: .fade)
        } else {
            tableView.deleteRows(at: [indexPath], with: .none)
        }
    }
    
    func displayError(viewModel: DesignPatterns.Error.ViewModel) {
        let alert = UIAlertController(
            title: "Ошибка",
            message: viewModel.message,
            preferredStyle: .alert
        )
        alert.addAction(UIAlertAction(title: "OK", style: .default))
        present(alert, animated: true)
    }
}
    

extension DesignPatternsViewController: PatternTableViewCellDelegate {
    func didTapFavorite(on cell: PatternTableViewCell) {
        guard let indexPath = tableView.indexPath(for: cell) else { return }
        let request = DesignPatterns.ToggleFavorite.Request(indexPath: indexPath)
        interactor?.toggleFavorite(request: request)
    }
}

