//
//  PatternDetailsNewPresenter.swift
//  ArchitecturePatternsAppV2
//
//  Created by Олег Зуев on 29.11.2025.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol PatternDetailsPresentationLogic {
    func presentPattern(response: PatternDetails.LoadPattern.Response)
}

class PatternDetailsPresenter: PatternDetailsPresentationLogic {
    
    weak var viewController: PatternDetailsDisplayLogic?
    
    func presentPattern(response: PatternDetails.LoadPattern.Response) {
        let patternVM = PatternViewModel(domain: response.patternModel)
        let viewModel = PatternDetails.LoadPattern.ViewModel(patternViewModel: patternVM)
        viewController?.displayPattern(viewModel: viewModel)
    }
}
