//
//  PatternDetailsNewWorker.swift
//  ArchitecturePatternsAppV2
//
//  Created by Олег Зуев on 29.11.2025.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

class PatternDetailsWorker {
    private let storage: PatternStorageProtocol
    
    init(storage: PatternStorageProtocol) {
        self.storage = storage
    }
    
    func getPattern(by id: UUID) throws -> PatternModel? {
        try storage.getPatternByID(id)
    }
    
    func updatePattern(with pattern: PatternModel) throws {
        try storage.updatePattern(pattern)
    }
    
}
