//
//  PatternDetailsNewInteractor.swift
//  ArchitecturePatternsAppV2
//
//  Created by Олег Зуев on 29.11.2025.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
import Foundation

protocol PatternDetailsBusinessLogic {
    func getPattern(request: PatternDetails.LoadPattern.Request)
    func updatePattern(request: PatternDetails.UpdatePattern.Request)
}

class PatternDetailsNewInteractor: PatternDetailsBusinessLogic {
    private let patternId: UUID
    private let worker: PatternDetailsWorker
    var presenter: PatternDetailsPresentationLogic?
    
    init(patternId: UUID, worker: PatternDetailsWorker) {
        self.patternId = patternId
        self.worker = worker
    }
    
    func getPattern(request: PatternDetails.LoadPattern.Request) {
        do {
            guard let pattern = try worker.getPattern(by: patternId) else { return }
            let response = PatternDetails.LoadPattern.Response(patternModel: pattern)
            presenter?.presentPattern(response: response)
        } catch {
            
        }
    }
    
    func updatePattern(request: PatternDetails.UpdatePattern.Request) {
        do {
            try worker.updatePattern(with: request.patternModel)
        } catch {
            
        }
    }

    
}
