//
//  PatternDetailsNewViewController.swift
//  ArchitecturePatternsAppV2
//
//  Created by Олег Зуев on 29.11.2025.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import PhotosUI

protocol PatternDetailsDisplayLogic: AnyObject {
    func displayPattern(viewModel: PatternDetails.LoadPattern.ViewModel)
}

class PatternDetailsViewController: RootViewController {
       
    // MARK: - Clean Swift
    var interactor: PatternDetailsBusinessLogic?
    var router: (NSObjectProtocol & PatternDetailsRoutingLogic)?
    
    // MARK: - UI Properties
    private var patternImage = UIImageView()
    private var editPhotoButton = UIButton(type: .system)
    private var patternTypeLabel = UILabel()
    private let chooseTypeButton = UIButton()
    
    private var patternName = UITextField()
    private var editButton: UIBarButtonItem!
    private let patternDescription = UITextView()
    
    // ViewModel
    private var draft: PatternViewModel?
    private var originalPattern: PatternViewModel?
    // MARK: - State
    private var isEditingMode = false
    
    // MARK: - Life cycle methods
    override func viewDidLoad() {
        super.viewDidLoad()
        setupView()
    }
    
    // MARK: - Objc methods
    @objc func didTapRightBarButton() {
        if isEditingMode {
            saveChanges()
            originalPattern = draft
        }
        toggleEditMode()
    }
    
    @objc func cancelEditing() {
        toggleEditMode()
        draft = originalPattern
        reloadView()
    }
    
    @objc func choosePatternTypeButtonTapped() {
        router?.showBottomSheet(selectedType: draft!.type)
    }
    
    @objc func didTapChoosePhotoButton() {
        router?.showImagePicker()
    }
    
    @objc func patternImageDidTap() {
        router?.showImageViewer(with: draft!.image)
    }
    
    private func saveChanges() {
    
        draft?.name = patternName.text ?? ""
        draft?.description = patternDescription.text
        draft?.image = patternImage.image ?? .no
        
        navigationItem.title = patternName.text
        
        let patternModel = PatternModel(viewModel: draft!)
        let request = PatternDetails.UpdatePattern.Request(patternModel: patternModel)
        interactor?.updatePattern(request: request)
    }

}

// MARK: - Private Methods
private extension PatternDetailsViewController {
    
    // MARK: - Setup View
    func setupView() {
        setupUI()
        setUpNavigationBar()
        addViews()
        setupConstraints()
        addActions()
        loadData()
    }
    
    // MARK: - Setup NavBar
    func setUpNavigationBar() {
        editButton = UIBarButtonItem(
            image: UIImage(resource: .editMode),
            style: .plain,
            target: self,
            action: #selector(didTapRightBarButton)
        )
        navigationItem.rightBarButtonItem = editButton
    }
    
    // MARK: - Setup UI
    func setupUI() {
        editPhotoButton.setTitle("Выбрать изображение", for: .normal)
        editPhotoButton.addTarget(self, action: #selector(didTapChoosePhotoButton), for: .touchUpInside)
        editPhotoButton.isHidden = true
        
        patternImage.layer.borderWidth = 1
        patternImage.layer.borderColor = UIColor.black.cgColor
        patternImage.layer.cornerRadius = 8
        patternImage.clipsToBounds = true
        
        patternName.font = UIFont(name: "SFPro-Semibold", size: 32)
        patternName.isEnabled = false
        patternName.rightView = UIImageView(image: UIImage(resource: .pencil))
        patternName.rightViewMode = .always
        patternName.rightView?.isHidden = true
        patternName.layer.borderWidth = 0
        patternName.layer.borderColor = UIColor.systemGray4.cgColor
        patternName.layer.cornerRadius = 8
        
        patternTypeLabel.textColor = .black
        patternTypeLabel.font = UIFont(name: "SFPro-Semibold", size: 20)
        
        chooseTypeButton.setImage(UIImage(resource: .chevronUP), for: .normal)
        chooseTypeButton.tintColor = .black
        chooseTypeButton.addTarget(self, action: #selector(choosePatternTypeButtonTapped), for: .touchUpInside)
        chooseTypeButton.isHidden = true
        
        patternDescription.font = UIFont(name: "SFPro-Regular", size: 16)
        patternDescription.isEditable = false
        patternDescription.isScrollEnabled = true
        patternDescription.layer.borderWidth = 0
        patternDescription.layer.borderColor = UIColor.systemGray4.cgColor
        patternDescription.layer.cornerRadius = 8
        
        self.view.backgroundColor = UIColor.systemBackground
    }
    
    // MARK: - Add Views
    func addViews() {
        view.addSubview(patternImage)
        view.addSubview(editPhotoButton)
        view.addSubview(patternName)
        view.addSubview(patternTypeLabel)
        view.addSubview(chooseTypeButton)
        view.addSubview(patternDescription)
    }
    
    // MARK: - Add Action
    
    func addActions() {
        patternImage.isUserInteractionEnabled = true
        
        let tapGesture = UITapGestureRecognizer(target: self, action: #selector(patternImageDidTap))
        patternImage.addGestureRecognizer(tapGesture)
    }
    // MARK: - Constraints Setup
    func setupConstraints() {
        let screenWidth = UIScreen.main.bounds.width
        
        patternImage.snp.makeConstraints { make in
            make.size.equalTo(screenWidth / 2)
            make.centerX.equalToSuperview()
            make.top.equalToSuperview().inset(100)
        }
        
        editPhotoButton.snp.makeConstraints { make in
            make.top.equalTo(patternImage.snp.bottom).offset(4)
            make.centerX.equalToSuperview()
        }
        
        patternName.snp.makeConstraints { make in
            make.top.equalTo(editPhotoButton.snp.bottom).offset(0)
            make.leading.equalToSuperview().offset(16)
            make.trailing.equalToSuperview().offset(-16)
        }
        
        patternTypeLabel.snp.makeConstraints { make in
            make.leading.equalTo(patternName)
            make.top.equalTo(patternName.snp.bottom).offset(24)
        }
        
        chooseTypeButton.snp.makeConstraints { make in
            make.bottom.top.equalTo(patternTypeLabel)
            make.trailing.equalTo(patternName)
            make.size.equalTo(24)
            
        }
        
        patternDescription.snp.makeConstraints { make in
            make.top.equalTo(patternTypeLabel.snp.bottom).offset(20)
            make.leading.trailing.equalToSuperview().inset(16)
            make.bottom.equalTo(view.safeAreaLayoutGuide.snp.bottom).inset(20)
        }
    }
    
    // MARK: - Toggle Edit Mode
    func toggleEditMode() {
        isEditingMode.toggle()
        self.patternImage.isUserInteractionEnabled = !self.isEditingMode
        self.editPhotoButton.isHidden = !self.isEditingMode
        self.patternName.isEnabled = self.isEditingMode
        self.patternName.rightView?.isHidden = !self.isEditingMode
        self.patternDescription.isEditable = self.isEditingMode
        self.patternName.rightView?.isHidden = !self.isEditingMode
        self.chooseTypeButton.isHidden = !self.isEditingMode
        self.patternDescription.layer.borderWidth = self.isEditingMode ? 1 : 0
        self.patternName.layer.borderWidth = self.isEditingMode ? 1 : 0
        self.editButton.image = UIImage(resource: self.isEditingMode ? .done : .editMode)
        navigationItem.leftBarButtonItem = isEditingMode ?  UIBarButtonItem(
            barButtonSystemItem: .cancel,
            target: self,
            action: #selector(cancelEditing)
        ) : nil
    }
    
    // MARK: - UpdateUI
    
    func reloadView() {
        guard let vm = draft else { return }
        navigationItem.title = vm.name
        patternName.text = vm.name
        patternDescription.text = vm.description
        patternTypeLabel.text = "Тип: \(vm.type.title)"
        patternImage.image = vm.image
    }
    
    func loadData() {
        let request = PatternDetails.LoadPattern.Request()
        interactor?.getPattern(request: request)
    }
}

// MARK: - Work with Image Methods
extension PatternDetailsViewController: PHPickerViewControllerDelegate {
    func picker(_ picker: PHPickerViewController, didFinishPicking results: [PHPickerResult]) {
        picker.dismiss(animated: true)
        
        guard let provider = results.first?.itemProvider else { return }
        
        if provider.canLoadObject(ofClass: UIImage.self) {
            provider.loadObject(ofClass: UIImage.self) { [weak self] image, _ in
                guard let image = image as? UIImage else { return }
                DispatchQueue.main.async {
                    self?.patternImage.image = image
                }
            }
        }
    }
}


// MARK: - PatternDetailsViewControllerDelegate
extension PatternDetailsViewController: BottomSheetDelegate {
    func updatePatternType(_ patternType: PatternType) {
        patternTypeLabel.text = "Тип: \(patternType.title)"
        draft?.type = patternType
    }
}

// MARK: - UI TextField Delegate
extension PatternDetailsViewController: UITextFieldDelegate {
    override func touchesBegan(_ touches: Set<UITouch>, with event: UIEvent?) {
        super.touchesBegan(touches, with: event)
        self.view.endEditing(true)
    }
}
extension PatternDetailsViewController: PatternDetailsDisplayLogic {
    func displayPattern(viewModel: PatternDetails.LoadPattern.ViewModel) {
        originalPattern = viewModel.patternViewModel
        draft = originalPattern
        reloadView()
    }
}
