//
//  PatternDetailsNewModels.swift
//  ArchitecturePatternsAppV2
//
//  Created by Олег Зуев on 29.11.2025.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
import Foundation


enum PatternDetails {
 
    // MARK: Use cases
    enum LoadPattern {
        struct Request {
        }
        
        struct Response {
            let patternModel: PatternModel
        }
        
        struct ViewModel {
            let patternViewModel: PatternViewModel
        }
    }
    
    enum UpdatePattern {
        struct Request {
            let patternModel: PatternModel
        }
    }
    
    enum Error {
        struct Response {
            let error: Error
        }
    }
    
    
}
