//
//  PatternDetailsNewRouter.swift
//  ArchitecturePatternsAppV2
//
//  Created by Олег Зуев on 29.11.2025.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import PhotosUI

protocol PatternDetailsRoutingLogic {
    func close()
    func showBottomSheet(selectedType: PatternType)
    func showImageSourceAlert()
    func showImagePicker()
    func showImageViewer(with image: UIImage)
}

class PatternDetailsNewRouter: NSObject, PatternDetailsRoutingLogic {
    weak var viewController: PatternDetailsViewController?
    
    func close() {
        viewController?.navigationController?.popViewController(animated: true)
    }
    
    func showBottomSheet(selectedType: PatternType) {
        let bottomSheet = BottomSheetViewController(selectedType: selectedType)
        bottomSheet.delegate = viewController
        viewController?.present(bottomSheet, animated: true)
    }
    
    func showImageSourceAlert() {
        let actionSheet = UIAlertController(title: nil, message: nil, preferredStyle: .actionSheet)
        let photo = UIAlertAction(title: "Фото", style: .default) { _ in
            self.showImagePicker()
        }
        let file = UIAlertAction(title: "Файлы", style: .destructive) { _ in
            // TODO Работа с файлами
        }
        
        let cancel = UIAlertAction(title: "Отмена", style: .cancel)
        
        actionSheet.addAction(photo)
        actionSheet.addAction(file)
        actionSheet.addAction(cancel)
        
        viewController?.present(actionSheet, animated: true)
    }
    
    func showImagePicker() {
        var config = PHPickerConfiguration(photoLibrary: .shared())
        config.filter = .images
        config.selectionLimit = 1
        
        let picker = PHPickerViewController(configuration: config)
        picker.delegate = viewController
        viewController?.present(picker, animated: true)
    }
    
    func showImageViewer(with image: UIImage) {
        let viewer = ImageViewerViewController(image: image)
        
        viewController?.navigationController?.pushViewController(viewer, animated: true)
    }
    
}
