//
//  PatternDetailsNewInteractor.swift
//  ArchitecturePatternsAppV2
//
//  Created by Олег Зуев on 29.11.2025.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
import Foundation

protocol PatternDetailsBusinessLogic {
    func getPattern(request: PatternDetails.LoadPattern.Request)
    func updatePattern(request: PatternDetails.UpdatePattern.Request)
}

class PatternDetailsNewInteractor: PatternDetailsBusinessLogic {
    private let patternId: UUID
    private let worker: PatternDetailsWorker
    var presenter: PatternDetailsPresentationLogic?
    
    init(patternId: UUID, worker: PatternDetailsWorker) {
        self.patternId = patternId
        self.worker = worker
    }
    
    func getPattern(request: PatternDetails.LoadPattern.Request) {
        worker.getPattern(by: patternId) { [weak self] result in
            guard let self else { return }
            
            switch result {
            case .success(let currentPattern):
                
                let response = PatternDetails.LoadPattern.Response(patternModel: currentPattern)
                
                DispatchQueue.main.async {
                    self.presenter?.presentPattern(response: response)
                }
            case .failure(let error):
                print("loadPattern failed", error)
            }
        }
    }
    
    func updatePattern(request: PatternDetails.UpdatePattern.Request) {
        let patternModel = request.patternModel
        worker.updatePattern(patternModel) { result in
            switch result {
            case .success():
                print("Pattern was updated")
            case.failure(let error):
                print("updatePattern failed", error)
            }
        }
    }

    
}
