//
//  FavoriteNewWorker.swift
//  ArchitecturePatternsAppV2
//
//  Created by Олег Зуев on 27.11.2025.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

class FavoriteWorker {
    private let storage: PatternStorageProtocol
    
    init(storage: PatternStorageProtocol) {
        self.storage = storage
    }
    
    func fetchFavoritePatterns() throws -> [PatternModel] {
        try storage.getFavoritePatterns()
    }
    
    func incrementViews(for model: PatternModel) throws {
        try storage.incrementViewCounterFor(model: model)
    }
}
