//
//  FavoriteNewModels.swift
//  ArchitecturePatternsAppV2
//
//  Created by Олег Зуев on 27.11.2025.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

enum Favorite {
 
    // MARK: Use cases
    enum LoadList {
        struct Request {
            
        }
        
        struct Response {
            let patterns: [PatternModel]
        }
        
        struct ViewModel {
            let rows: [PatternViewModel]
        }
    }
    
    enum Select {
        struct Request {
            let indexPath: IndexPath
        }
    }
    
    enum Error {
        struct Response {
            let error: Error
        }
    }
}
