//
//  FavoriteNewViewController.swift
//  ArchitecturePatternsAppV2
//
//  Created by Олег Зуев on 27.11.2025.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FavoriteDisplayLogic: AnyObject {
    func displayFavorite(viewModel: Favorite.LoadList.ViewModel)
}

class FavoriteViewController: BaseContentViewController {
    
    // MARK: - CleanSwift
    var interactor: FavoriteBusinessLogic?
    var router: (NSObjectProtocol & FavoriteRoutingLogic & FavoriteDataPassing)?
    
    // MARK: - Properties
    private var tableView = UITableView()
    private var data: [PatternViewModel] = []
    
    // MARK: - Life cycle methods
    
    override func viewDidLoad() {
        super.viewDidLoad()
        setupView()
        loadFavorite()
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        loadFavorite()
    }
    
    @objc override func didTapRightButton() {
        router?.toggleSideMenu()
    }
    
    private func loadFavorite() {
        let request = Favorite.LoadList.Request()
        interactor?.loadFavoritePatterns(request: request)
    }
}

// MARK: - Private Methods
private extension FavoriteViewController {
    
    // MARK: - View Setup
    func setupView() {
        setupUI()
        setupTableView()
        addViews()
        setupConstraints()
    }
    
    // MARK: - UI Setup
    func setupUI() {
        self.view.backgroundColor = UIColor.systemBackground
        self.navigationItem.leftBarButtonItem = nil
        title = "Избранное"
    }
    
    // MARK: - Table Setup
    func setupTableView() {
        tableView.register(PatternTableViewCell.self, forCellReuseIdentifier: PatternTableViewCell.identifier)
        tableView.register(HeaderView.self, forHeaderFooterViewReuseIdentifier: HeaderView.identifier)
        tableView.delegate = self
        tableView.dataSource = self
        tableView.separatorStyle = .none
        tableView.sectionHeaderTopPadding = 0
    }
    
    // MARK: - Add Views
    func addViews() {
        view.addSubview(tableView)
    }
    
    // MARK: - Constraints Setup
    func setupConstraints() {
        tableView.snp.makeConstraints { make in
            make.edges.equalToSuperview()
        }
    }
}

// MARK: - UITableViewDataSource
extension FavoriteViewController: UITableViewDataSource {
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        data.count
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        guard let cell = tableView.dequeueReusableCell(withIdentifier: PatternTableViewCell.identifier, for: indexPath) as? PatternTableViewCell else { return UITableViewCell() }
        
        let viewModel = data[indexPath.row]
        
        cell.configure(with: viewModel, isFirstCell: indexPath.row == 0)
        
        return cell
    }
}

// MARK: - UITableViewDelegate
extension FavoriteViewController: UITableViewDelegate {
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        let request = Favorite.Select.Request(indexPath: indexPath)
        interactor?.selectPattern(request: request)
        router?.openPatternDetails()
    }
}

// MARK: - CleanSwift
extension FavoriteViewController: FavoriteDisplayLogic {
    func displayFavorite(viewModel: Favorite.LoadList.ViewModel) {
        data = viewModel.rows
        tableView.reloadData()
    }
}

