//
//  FavoriteNewPresenter.swift
//  ArchitecturePatternsAppV2
//
//  Created by Олег Зуев on 27.11.2025.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol FavoritePresentationLogic {
    func presentFavorite(response: Favorite.LoadList.Response)
}

class FavoritePresenter: FavoritePresentationLogic {
    
    weak var viewController: FavoriteDisplayLogic?
    
    func presentFavorite(response: Favorite.LoadList.Response) {
        let rowsVM: [PatternViewModel] = response.patterns.map { domainPattern in
            return .init(domain: domainPattern)
        }
        
        let viewModel = Favorite.LoadList.ViewModel(rows: rowsVM)
        viewController?.displayFavorite(viewModel: viewModel)
    }
}
