//
//  FavoriteNewRouter.swift
//  ArchitecturePatternsAppV2
//
//  Created by Олег Зуев on 27.11.2025.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol FavoriteRoutingLogic {
    func openPatternDetails()
    func toggleSideMenu()
}

protocol FavoriteDataPassing {
    var dataStore: FavoriteDataStore? { get }
}

class FavoriteRouter: NSObject, FavoriteRoutingLogic, FavoriteDataPassing {
    
    weak var viewController: FavoriteViewController?
    var dataStore: FavoriteDataStore?
    
    func openPatternDetails() {
        guard let patternID = dataStore?.selectedPattern?.id else { return }
        
        let vc = GlobalBuilder.create(.patternDetails(patternID))
        viewController?.navigationController?.pushViewController(vc, animated: true)
    }
    
    func toggleSideMenu() {
        guard let nav = viewController?.navigationController,
              let container = nav.parent as? ContainerRouting else { return }
        
        container.toggleSideMenu(nil)
    }
}
