//
//  FavoriteNewWorker.swift
//  ArchitecturePatternsAppV2
//
//  Created by Олег Зуев on 27.11.2025.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

class FavoriteWorker {
    private let remoteStore: PatternRemoteStoreProtocol

    init(remoteStore: PatternRemoteStoreProtocol) {
        self.remoteStore = remoteStore
    }
    
    func fetchFavPatterns(completion: @escaping (Result<[PatternModel], Error>) -> Void) {
        remoteStore.fetchFavorite(completion: completion)
    }
    
    func incrementViewCounterFor(_ model: PatternModel, completion: ((Result<Void, Error>) -> Void)?) {
        remoteStore.incrementViewCounterFor(model, completion: completion)
    }
}
