//
//  FavoriteNewInteractor.swift
//  ArchitecturePatternsAppV2
//
//  Created by Олег Зуев on 27.11.2025.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

protocol FavoriteBusinessLogic {
    func loadFavoritePatterns(request: Favorite.LoadList.Request)
    func selectPattern(request: Favorite.Select.Request)
}

protocol FavoriteDataStore {
    var rows: [PatternModel] { get set }
    var selectedPattern: PatternModel? { get set }
}

class FavoriteInteractor: FavoriteBusinessLogic, FavoriteDataStore {
   
    var presenter: FavoritePresentationLogic?
    let worker: FavoriteWorker
    
    var rows: [PatternModel] = []
    var selectedPattern: PatternModel?
    
    init(worker: FavoriteWorker) {
        self.worker = worker
    }
    
    func loadFavoritePatterns(request: Favorite.LoadList.Request) {
        do {
            let favPatterns = try worker.fetchFavoritePatterns()
            rows = favPatterns
            let response = Favorite.LoadList.Response(patterns: favPatterns)
            presenter?.presentFavorite(response: response)
        } catch {
            // Тут можно обработать ошибку
        }
    }
    
    func selectPattern(request: Favorite.Select.Request) {
        let indexPath = request.indexPath
        guard rows.indices.contains(indexPath.row) else { return }
        selectedPattern = rows[indexPath.row]
        
        
        do {
            try worker.incrementViews(for: selectedPattern!)
        } catch {
            // Тут можно обработать ошибку
        }
    }
}
