//
//  FavoriteNewInteractor.swift
//  ArchitecturePatternsAppV2
//
//  Created by Олег Зуев on 27.11.2025.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

protocol FavoriteBusinessLogic {
    func loadFavoritePatterns(request: Favorite.LoadList.Request)
    func selectPattern(request: Favorite.Select.Request)
}

protocol FavoriteDataStore {
    var rows: [PatternModel] { get set }
    var selectedPattern: PatternModel? { get set }
}

class FavoriteInteractor: FavoriteBusinessLogic, FavoriteDataStore {
   
    var presenter: FavoritePresentationLogic?
    let worker: FavoriteWorker
    
    var rows: [PatternModel] = []
    var selectedPattern: PatternModel?
    
    init(worker: FavoriteWorker) {
        self.worker = worker
    }
    
    func loadFavoritePatterns(request: Favorite.LoadList.Request) {
        worker.fetchFavPatterns { [weak self] result in
            guard let self else { return }
            
            switch result {
            case .success(let favPatterns):
                
                self.rows = favPatterns
                let response = Favorite.LoadList.Response(patterns: favPatterns)
                
                DispatchQueue.main.async {
                    self.presenter?.presentFavorite(response: response)
                }
                
            case .failure(let error):
                print("loadPattern failed", error)
            }
        }
    }
    
    func selectPattern(request: Favorite.Select.Request) {
        let indexPath = request.indexPath
        guard rows.indices.contains(indexPath.row) else { return }
        selectedPattern = rows[indexPath.row]
        
        worker.incrementViewCounterFor(selectedPattern!) { result in
            if case let .failure(error) = result {
                print("incrementCounter failed", error)
            }
        }
    }
}
