//
//  DesignPatternsCSWorker.swift
//  ArchitecturePatternsAppV2
//
//  Created by Олег Зуев on 25.11.2025.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
import Foundation

class DesignPatternsCSWorker {
    private let storage: PatternStorageProtocol
    
    init(storage: PatternStorageProtocol) {
        self.storage = storage
    }
    
    func fetchAllPatterns() throws -> [Pattern] {
        try storage.getAllPatterns()
    }
    
    func updatePattern(_ pattern: PatternModel) throws {
        try storage.updatePattern(pattern)
    }
    
    func deletePattern(_ pattern: PatternModel) throws {
        try storage.removePattern(pattern)
    }
    
    func incrementViews(for pattern: PatternModel) throws {
        try storage.incrementViewCounterFor(pattern: pattern)
    }
}
