//
//  DesignPatternsCSPresenter.swift
//  ArchitecturePatternsAppV2
//
//  Created by Олег Зуев on 25.11.2025.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol DesignPatternsCSPresentationLogic {
    func presentSomething(response: DesignPatternsCS.Something.Response)
}

class DesignPatternsCSPresenter: DesignPatternsCSPresentationLogic {
    
    weak var viewController: DesignPatternsCSDisplayLogic?
    
    func presentSomething(response: DesignPatternsCS.Something.Response) {
        let viewModel = DesignPatternsCS.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
