//
//  DesignPatternsCSPresenter.swift
//  ArchitecturePatternsAppV2
//
//  Created by Олег Зуев on 25.11.2025.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

protocol DesignPatternsCSPresentationLogic {
    func presentPatterns(response: DesignPatternsCS.LoadList.Response)
    func presentRowUpdate(response: DesignPatternsCS.RowUpdate.Response)
    func presentRowDeletion(response: DesignPatternsCS.RowDelete.Response)
    func presentError(response: DesignPatternsCS.Error.Response)
}

class DesignPatternsCSPresenter: DesignPatternsCSPresentationLogic {
    
    weak var viewController: DesignPatternsCSDisplayLogic?
    
    func presentPatterns(response: DesignPatternsCS.LoadList.Response) {
        let sectionsVM: [DesignPatternsCS.LoadList.ViewModel.Section] =
        response.sections.enumerated().map { (sectionsIndex, patterns) in
            let type = patterns.first?.type ?? PatternType.creational
            let sectionTitle = type.title
            
            let rows = patterns.map { pattern in
                DesignPatternsCS.LoadList.ViewModel.Row(
                    id: pattern.id,
                    title: pattern.name,
                    subtitle: pattern.description ?? "",
                    typeTitle: pattern.type.title,
                    isFavorite: pattern.isFavorite,
                    viewCounterText: "\(pattern.viewCounter) просмотров"
                )
            }
            return .init(title: sectionTitle, rows: rows)
        }
    }
    
    func presentRowUpdate(response: DesignPatternsCS.RowUpdate.Response) {
        let vm = DesignPatternsCS.RowUpdate.ViewModel(indexPath: response.indexPath)
        viewController?.displayRowUpdate(viewModel: vm)
    }
    
    func presentRowDeletion(response: DesignPatternsCS.RowDelete.Response) {
        <#code#>
    }
    
    func presentError(response: DesignPatternsCS.Error.Response) {
        <#code#>
    }
    
}
