//
//  DesignPatternsCSViewController.swift
//  ArchitecturePatternsAppV2
//
//  Created by Олег Зуев on 25.11.2025.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DesignPatternsCSDisplayLogic: AnyObject {
    func displayRowUpdate(viewModel: DesignPatternsCS.RowUpdate.ViewModel)
    func displayRowDeletion(viewModel: DesignPatternsCS.RowDelete.ViewModel)
}

class DesignPatternsCSViewController: UIViewController {
        
    var interactor: DesignPatternsCSBusinessLogic?
    var router: (NSObjectProtocol & DesignPatternsCSRoutingLogic & DesignPatternsCSDataPassing)?
    
    // MARK: Object lifecycle
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: View lifecycle
    override func viewDidLoad() {
        super.viewDidLoad()
        doSomething()
    }
    
    // MARK: Routing
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
        
    private func doSomething() {
        let request = DesignPatternsCS.LoadList.Request()
        interactor?.doSomething(request: request)
    }
    
    // MARK: Setup
    private func setup() {
        let viewController = self
        let interactor = DesignPatternsCSInteractor()
        let presenter = DesignPatternsCSPresenter()
        let router = DesignPatternsCSRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
}

extension DesignPatternsCSViewController: DesignPatternsCSDisplayLogic {
    func displaySomething(viewModel: DesignPatternsCS.LoadList.ViewModel) {
        
    }
}
