//
//  DesignPatternsCSInteractor.swift
//  ArchitecturePatternsAppV2
//
//  Created by Олег Зуев on 25.11.2025.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol DesignPatternsCSBusinessLogic {
    func doSomething(request: DesignPatternsCS.Something.Request)
}

protocol DesignPatternsCSDataStore {
    
}

class DesignPatternsCSInteractor: DesignPatternsCSBusinessLogic, DesignPatternsCSDataStore {
    
    var presenter: DesignPatternsCSPresentationLogic?
    var worker: DesignPatternsCSWorker?
    
    func doSomething(request: DesignPatternsCS.Something.Request) {
        worker = DesignPatternsCSWorker()
        worker?.doSomeWork()
        
        let response = DesignPatternsCS.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
